### ISSUE TITLE
Users can type a space into the search box and click search - causes a 500 on the server

### ISSUE THREAD

**Issue by walkeriniraq** [walkeriniraq/twitarr#191]
Client should not allow a blank search.

**Comment by walkeriniraq** [comment]
Fixed.

**Comment by walkeriniraq** [comment]
No longer causes a 500 but it breaks the javascript

**Comment by Wingar** [comment]
Symbols like \, /, : also cause it.

**Comment by Wingar** [comment]
So, I devised a few quick gsubs on the search parameters on the search controller, it's a hacky way of escaping but it seems to do the trick *AND* it seems to fix the javascript breaking problem. I'm not sure how, to be honest.

**Comment by Wingar** [comment]
I'm still not sure this covers everything, I don't want to close it just yet. I'll do more testing to see if I can break it.

**Comment by Wingar** [comment]
Yeah, I'm gonna call this fixed now. I can't seem to break it any more.
